### ISSUE TITLE
Help Can't Sketch ESP32S2

### ISSUE THREAD

**Issue by neo305** [lorol/arduino-esp32fs-plugin#10]
stooged please help. It is impossible to install everything that is needed for Arduino. I think it says I am missing esptool.py?
Arduino: 1.8.19 (Windows 10), Board: "ESP32S2 Dev Module, Disabled, Disabled, Disabled, UART0, Disabled, No OTA (1MB APP/3MB SPIFFS), 240MHz (WiFi), QIO, 80MHz, 16MB (128Mb), 921600, None"

Chip : esp32s2

Using partition scheme from Arduino IDE.

Start: 0x110000

Size : 0x2f0000

mkspiffs : C:\Users\laz30\AppData\Local\Arduino15\packages\esp32\tools\mkspiffs\0.2.3\mkspiffs.exe

esptool : C:\Users\laz30\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\3.1.0\esptool.exe

[SPIFFS] data   : C:\Users\laz30\Documents\Arduino\ESP32_Server_900u\data

[SPIFFS] offset : 0

[SPIFFS] start  : 1114112

[SPIFFS] size   : 3008

[SPIFFS] page   : 256

[SPIFFS] block  : 4096

->/1.jpg.gz

->/2.jpg.gz

->/3.jpg.gz

->/4.jpg.gz

->/5.jpg.gz

->/6.jpg.gz

->/disableupdates.bin.gz

->/fanthreshold.js.gz

->/gamedumper.bin.gz

->/goldhen_2.1.bin.gz

->/henplatinum1b.bin.gz

->/index.html

->/MakeCache.bat

->/OrbisToolbox.bin.gz

->/ps4debug.bin.gz

->/Style.css.gz

->/theme.html.gz

->/webactivator.js.gz

->/webrte.bin.gz

[SPIFFS] upload : C:\Users\laz30\AppData\Local\Temp\arduino_build_395582/ESP32_Server_900u.spiffs.bin

[SPIFFS] address: 1114112

[SPIFFS] port   : COM8

[SPIFFS] speed  : 921600

[SPIFFS] mode   : dio

[SPIFFS] freq   : 80m

->esptool.py v3.1

->Serial port COM8

_>Traceback (most recent call last):

_>  File "esptool.py", line 4582, in <module>

_>  File "esptool.py", line 4575, in _main

_>  File "esptool.py", line 4074, in main

_>  File "esptool.py", line 121, in get_default_connected_device

_>  File "esptool.py", line 629, in connect

_>  File "esptool.py", line 596, in _connect_attempt

_>  File "esptool.py", line 486, in sync

_>  File "esptool.py", line 418, in command

_>  File "serial\serialutil.py", line 372, in timeout

_>  File "serial\serialwin32.py", line 222, in _reconfigure_port

_>serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: OSError(22, 'A device which does not exist was specified.', None, 433)

->Connecting...

_>[4896] Failed to execute script esptool

SPIFFS Upload failed!

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by neo305** [comment]
Arduino: 1.8.19 (Windows 10), Board: "ESP32S2 Dev Module, Disabled, Disabled, Disabled, UART0, Disabled, No OTA (1MB APP/3MB FATFS), 240MHz (WiFi), QIO, 80MHz, 16MB (128Mb), 921600, None"

Chip : esp32s2

Using partition scheme from Arduino IDE.

Start: 0x111000

Size : 0x2ef000



FatFS Error: mkfatfs.exe not found!



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
