### ISSUE TITLE
FFat upload impossible (solved)

### ISSUE THREAD

**Issue by lesept777** [lorol/arduino-esp32fs-plugin#18]
Hi
When trying to upload files to a FFat partition, I get this error message:

```
Chip : esp32s3
Using partitions.csv from sketch folder.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.esp32.mkspiffs.ESP32FS.createAndUpload(ESP32FS.java:282)
	at com.esp32.mkspiffs.ESP32FS.run(ESP32FS.java:579)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
String index out of range: -1
```

I'm using Arduino IDE 1.8.19, the `partitions.csv `file is as follows:

```
# Name,   Type, SubType,  Offset,   Size,  Flags
nvs, data, nvs, 0x9000, 0x5000
otadata, data, ota, 0xE000, 0x2000
factory, app, factory, 0x10000, 0xC8000
ffat, data, fat, 0xD8000, 0xF18000
coredump, data, coredump, 0xFF0000, 0x10000

```
and I chose the option `custom` for the Partition scheme.

What is wrong?
Thanks for your help.

**Comment by lesept777** [comment]
I simplified the problem, with an empty code (setup and loop are empty), and partition from the list 16MB Flash (3MB apAPP/9.9MB FATFS)
The data folder contains only a very small txt file and the upload works.

So the problem is related either to the custom partition or its size.

**Comment by lesept777** [comment]
Solved!
It seems the partitions file needs to have , at the end of each line

```
# Name,   Type, SubType,  Offset,   Size,  Flags
nvs, data, nvs, 0x9000, 0x5000,
otadata, data, ota, 0xE000, 0x2000,
factory, app, factory, 0x10000, 0xC8000,
ffat, data, fat, 0xD8000, 0xF18000,
coredump, data, coredump, 0xFF0000, 0x10000,
```
